import type { ContentFingerprint, SeoWriterInput, SeoWriterOutput } from "./types";
interface AnthropicResponse { model?:string; stop_reason?:string; content?:Array<{type:string;text?:string}>; usage?:{input_tokens?:number;output_tokens?:number}; }
const ANTHROPIC_API_URL="https://api.anthropic.com/v1/messages"; const DEFAULT_MODEL="claude-sonnet-5";
const SYSTEM_PROMPT=`You are the MANUFACTURER WRITER for BodyNutrition.biz, downstream from SEO Radar.
Never invent brand history, founding date, founders, headquarters, country of origin, ownership, manufacturing location, certifications, awards, distribution, product ranges, claims, URLs or commercial relationships.
Only VERIFIED CATALOG FACTS and CATALOG EVIDENCE are confirmed facts about the manufacturer and BodyNutrition assortment. Existing content is context, not verified truth. SEO evidence is search evidence, not brand evidence.
Write a useful manufacturer/brand landing page around verified assortment, product families, formats and selection criteria. Do not fabricate a corporate biography. If the dossier lacks facts needed for a claim, omit it and add a warning.
Use health/performance claims only when explicitly verified. Never transfer generic ingredient benefits to all products of a brand.
Use only VERIFIED INTERNAL LINKS and never alter URLs. Do not add H1 because the template renders it.
For INTEGRARE preserve useful verified material; for RISCRIVERE replace weak/unverified copy while retaining requested facts.
Avoid generic brand superlatives such as leader, premium, renowned, innovative unless verified.
main_description = long brand/manufacturer SEO content. additional_description = concise introductory block; do not duplicate main_description.
Study editorial fingerprints and avoid recycled structures. Return only schema JSON and a truthful fingerprint.`;
const SCHEMA={type:"object",properties:{meta_title:{type:"string"},meta_description:{type:"string"},main_description:{type:"string"},additional_description:{type:"string"},warnings:{type:"array",items:{type:"string"}},fingerprint:{type:"object",properties:{opening:{type:"string"},h2_structure:{type:"array",items:{type:"string"}},editorial_angle:{type:"string"},cta_patterns:{type:"array",items:{type:"string"}},faq_topics:{type:"array",items:{type:"string"}},structure_type:{type:"string"},catalog_evidence_used:{type:"array",items:{type:"string"}},serp_gap_used:{type:"string"}},required:["opening","h2_structure","editorial_angle","cta_patterns","faq_topics","structure_type","catalog_evidence_used","serp_gap_used"],additionalProperties:false}},required:["meta_title","meta_description","main_description","additional_description","warnings","fingerprint"],additionalProperties:false};
function clean(v:unknown){return typeof v==="string"?v.replace(/^[\uFEFF\u200B-\u200D\uFEFF]/g,"").replace(/[\r\n]/g,"").replace(/^["']|["']$/g,"").trim():"";}
function dossier(i:SeoWriterInput){return `BODYNUTRITION MANUFACTURER DOSSIER\nMARKET: ${i.market}\nLANGUAGE: ${i.language}\nPAGE ID: ${i.pageId??"not supplied"}\nURL: ${i.url??"not supplied"}\nDECISION: ${i.decision}\nCLUSTER: ${i.cluster??"not supplied"}\nSEARCH INTENT: ${i.searchIntent}\nPRIMARY KEYWORD: ${i.primaryKeyword}\nSECONDARY KEYWORDS: ${JSON.stringify(i.secondaryKeywords??[],null,2)}\n\nEDITORIAL ANGLE\n${i.proposedEditorialAngle??"not supplied"}\n\nSERP GAP\n${i.serpGap??"not supplied"}\n\nVERIFIED CATALOG / BRAND FACTS\n${JSON.stringify(i.verifiedCatalogFacts??[],null,2)}\n\nCATALOG EVIDENCE\n${JSON.stringify(i.catalogEvidence??[],null,2)}\n\nSEO EVIDENCE\n${JSON.stringify(i.seoEvidence??[],null,2)}\n\nVERIFIED INTERNAL LINKS\n${JSON.stringify(i.verifiedInternalLinks??[],null,2)}\n\nEXISTING CONTENT — UNVERIFIED CONTEXT\n${i.existingContent??"not supplied"}\n\nCONTENT TO PRESERVE\n${JSON.stringify(i.contentToPreserve??[],null,2)}\n\nEDITORIAL MEMORY\n${JSON.stringify(i.priorFingerprints??[],null,2)}\n\nRADAR INSTRUCTIONS\n${i.instructions??"none"}`;}
export async function writeManufacturerContent(apiKeyRaw:string,input:SeoWriterInput,model=DEFAULT_MODEL):Promise<{provider:"anthropic";model:string;content:SeoWriterOutput;usage?:{input_tokens?:number;output_tokens?:number}}>{
 const apiKey=clean(apiKeyRaw), selectedModel=model?.trim()||DEFAULT_MODEL; if(!apiKey)throw new Error("ANTHROPIC_API_KEY is not configured."); if(input.pageType!=="manufacturer")throw new Error("Manufacturer Writer only accepts pageType=manufacturer."); if(!input.language?.trim()||!input.market?.trim()||!input.searchIntent?.trim()||!input.primaryKeyword?.trim())throw new Error("language, market, searchIntent and primaryKeyword are required.");
 const r=await fetch(ANTHROPIC_API_URL,{method:"POST",headers:{"content-type":"application/json","x-api-key":apiKey,"anthropic-version":"2023-06-01"},body:JSON.stringify({model:selectedModel,max_tokens:8000,system:SYSTEM_PROMPT,messages:[{role:"user",content:dossier(input)}],output_config:{format:{type:"json_schema",schema:SCHEMA}}})}); const raw=await r.text(); if(!r.ok)throw new Error(`Anthropic API error ${r.status}: ${raw.slice(0,1500)}`); let data:AnthropicResponse;try{data=JSON.parse(raw);}catch{throw new Error("Anthropic returned an invalid API response.");} if(data.stop_reason==="refusal"||data.stop_reason==="max_tokens"||(data.stop_reason&&data.stop_reason!=="end_turn"))throw new Error(`Anthropic Manufacturer Writer stopped: ${data.stop_reason}.`); const b=data.content?.find(x=>x.type==="text"&&typeof x.text==="string");if(!b?.text)throw new Error("Anthropic returned no structured text content.");let content:SeoWriterOutput;try{content=JSON.parse(b.text);}catch{throw new Error("Anthropic structured output could not be parsed.");} if(!content.meta_title?.trim()||!content.meta_description?.trim()||!content.main_description?.trim()||!content.additional_description?.trim())throw new Error("Manufacturer Writer returned incomplete fields."); if(/<h1\b/i.test(content.main_description))throw new Error("Manufacturer Writer returned an H1."); const fp=content.fingerprint as ContentFingerprint|undefined;if(!fp)throw new Error("Manufacturer Writer returned no fingerprint.");fp.entity_type="manufacturer";fp.entity_id=input.pageId;fp.language=input.language;fp.market=input.market;fp.cluster=input.cluster;fp.writer_model=data.model??selectedModel;return{provider:"anthropic",model:data.model??selectedModel,content,usage:data.usage};
}
